OVDotCom/Models/BlogModel.cs
using System;

namespace OllieVaughanDotCom.Models
{
    public class BlogModel
    {
        public long Id { get; set; }
        public string Author { get; set; }
        public DateTime Date { get; set; }
        public string Content { get; set; }
        public int Order { get; set; }
        public bool Done { get; set; }

    }
}

OVDotCom/Controllers/BlogController.cs
using System.Web.Mvc;

namespace OVDotCom.Controllers
{
    public class BlogController : Controller
    {
        public ActionResult AddBlog()
        {
            return View();
        }

        public ActionResult ViewBlogs()
        {
            return View();
        }
    }
}

OVDotCom/Controllers/HomeController.cs
using System.Web.Mvc;
using OVDotCom.Utils;

namespace OVDotCom.Controllers
{
    public class HomeController : Controller
    {
        private IUtils Utils { get; set; }

        public HomeController(IUtils utils)
        {
            Utils = utils;
        }
        
        public ActionResult Index()
        {
            return View();
        }

    }
}

OVDotCom/Views/Blog/AddBlog.cshtml
@{
    ViewBag.Title = "New blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add a new blog</h2>

OVDotCom/Views/Blog/ViewBlogs.cshtml
@{
    ViewBag.Title = "View Blogs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View current blogs</h2>

OVDotCom/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Intro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Intro</h2>
<br/>

OVDotCom/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Oliver Vaughan</title>
        <meta name="viewport" content="width=device-width" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">
        @Styles.Render("~/Content/css")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home") | </li>
                        <li>@Html.ActionLink("Add", "AddBlog", "Blog") | </li>
                        <li>@Html.ActionLink("View", "ViewBlogs", "Blog")</li>
                    </ul>
                </nav>
            </div>
        </header>
        <div id="body">
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </div>
        <footer>
            <div class="content-wrapper">
                <p>&copy; @DateTime.Now.Year - Oliver Vaughan</p>
            </div>
        </footer>
    </body>
</html>